### ISSUE TITLE
Sbt, Mill, Metals, VsCode, Sublime and IntelliJ.

### ISSUE THREAD

**Issue by richtype** [richtype/openstrat#10]

**Comment by Richtype** [comment]
So Mill is currently working for runBackground and test. Neither Mill or sbt are currently working properly for creating Intelij projects.

**Comment by richtype** [comment]
So continuing to use both Mill and Sbt for builds. Started using VScode with Metals. Will leave this issue open, modify title and remove high-prority label.

**Comment by richtype** [comment]
Obviously this is going to be an ongoing issues, but with the move to 2.13, there is a plan for the ensuing months. We will continue to use both Mill and Sbt. We will use IntelliJ Idea and VSCode as editors using Metals. Hence closing.
