### ISSUE TITLE
Change root package name from "rich"

### ISSUE THREAD

**Issue by Richtype** [Richtype/openstrat#11]
I chose the name "rich" as a root package name when all my code was closed source. It tied in with my use of the richstrat.com domain. I intend to keep richstrat.com as my own privately owned domain and richstrat as my own private marketing name if I decide to commercialise my work in the future. The use of package name is therefore potentially imprecise and misleading.

Possible replacements "ostrat".

**Comment by w0d** [comment]
rich -> openstrat?

**Comment by Richtype** [comment]
@w0d I think its better if the package name is different from the project name. Scala default practice is to use the organisation domain name, usually," org.something.somethingelse", but as this is no organisation domain, that can't be followed.

**Comment by w0d** [comment]
any reason for not getting a domain for openstrat?
for me, a holding page with links to here and other channels makes more sense than effort?

**Comment by Richtype** [comment]
I have committed the changes but will wait before closing the issue.

**Comment by Richtype** [comment]
@w0d I'm happy if you or someone else at a later point wants to take that initiative. I'm displaying stuff on my own site richstrat.com, but anyone can display stuff on their own site or create an organisation one, if they want.

**Comment by w0d** [comment]
@Richtype i'm being cautious in waiting for #17 to be solved before closing this one..
