### ISSUE TITLE
jsBothPlay.html => ReferenceError: ostrat is not defined

### ISSUE THREAD

**Issue by w0d** [Richtype/openstrat#17]
offending line 10:
`<script type='text/javascript'>ostrat.pSJs.JsPlay().main();</script>`

**Comment by w0d** [comment]
#11

**Comment by w0d** [comment]
I've commented out line 10 and as far as i can see everything works
any thoughts @Richtype

**Comment by Richtype** [comment]
Fix looks good but will check with Scala.js gitter about the offending line.

**Comment by Richtype** [comment]
The line became obsolete when using `scalaJSUseMainModuleInitializer := true` in sbt.

**Comment by w0d** [comment]
:+1:
