### ISSUE TITLE
Page display and unwanted scroll bars in html pages

### ISSUE THREAD

**Issue by Richtype** [Richtype/openstrat#19]

**Comment by Richtype** [comment]
@w0d will clarify precise problems.

**Comment by w0d** [comment]
unwanted scroll bars removed

**Comment by Richtype** [comment]
I doubt it, or if there was a reason its probably gone. I might have intended the user to be able to see the text below the canvas. Make any adjustments you see fit. This looks good to me, but I'll leave it to you to close, when you're happy with it, as I'm not fully conversant with the details.
