### ISSUE TITLE
Cleanup, Improvement and Documentation of the geom package

### ISSUE THREAD

**Issue by richtype** [richtype/openstrat#59]
The aim is to get the package up to an acceptable library in development standard, in terms of api / code, formatting and documentation. A full test suite for the package would be desirable but is not essential to have this issue signed off. This can be done in conjunction with work on the lessons whose major focus is this package.

**Comment by richtype** [comment]
I'm going to close this as no input from @w0d for a while. Clean up is ongoing, but too many priorites to continue this as a special focus.

**Comment by Rich2** [comment]
That was a mistake should have referenced #79.
