### ISSUE TITLE
Try to move Appnum setting to home directory 

### ISSUE THREAD

**Issue by richtype** [richtype/openstrat#61]
This will hopefully allow the setting to be monitored for changes by Mill and Sbt by using a symlink to the Dev sub directory, but ignored by git.

**Comment by Richtype** [comment]
I'm finding it tricky to watch the home directory in Mill and Sbt, so I am going to put this issue on the back burner.

**Comment by richtype** [comment]
appNum is now in ~/AppData/Local/OpenStrat/DevSettings.rson
