### ISSUE TITLE
findTypeIndex failing in LessonD1

### ISSUE THREAD

**Issue by w0d** [richtype/openstrat#63]
changing  line 12 in lessonD1
val r4 = str.findTypeIndex[String](2)
to a valid index such as
val r4 = str.findTypeIndex[String](0)
still returns a error: Str not Found

**Comment by Richtype** [comment]
So the purpose of findType[A] is for extremely rapid prototyping and to that end I think it would be useful to have findInt, findTypeIndex[A](index: Int) and findInt(index: Int). However it not intended to have multiple values in a file for production resources. The intention is to use settings. Why would one want multiple, unlabelled values in a production resource file. But why also would one want even single unlabelled values of common types in a file for production resources.

So I therefore while I think findFlt[A], findBool[A], findFltIndex[A](index: Int) and findBoolIndex(index: Int) should be added.

I think findFirstType should be removed and no findString should be added as strings are not quick to write and so are not useful for extremely rapid prototyping.

**Comment by richtype** [comment]
Error no longer makes sense so closing.
