### ISSUE TITLE
Audio for Library

### ISSUE THREAD

**Issue by w0d** [richtype/openstrat#69]
There's currently no audio in the library, and im interested in understanding how that could be implemented

**Comment by richtype** [comment]
I currently feel too overloaded with tasks to even look into this, even in a minimal way. So I'm going to remove my assignment.

**Comment by w0d** [comment]
Scalajs has hooks for the Web API Audio Context, which is making me think if there's other HTML audio things that they would be within easy reach. Think that's cleared most of the fog.. I wont look into jfx now until things a bit more certain that way..

**Comment by richtype** [comment]
I've edited the README, so all info is in there. Can this be closed now? I haven't closed it myself as I'm no longer an assignee.
